const projects = [
    {
        id: 1,
        name: "Portfolio Website",
        description: "A personal portfolio website to showcase my projects and skills.",
        detailedDescription:"More things to explain here.",
        technologies: ["HTML", "CSS", "JavaScript", "React"],
        link: "https://github.com/NkaLight/myWebsite/blob/main/README.md",
        skillDescription: "Modern Client-side Web development",
        startDate: "2023-05-10",
        endDate: "present",
    },
    {
        id: 2,
        name: "Tech store",
        description: "An e-commerce platform for small businesses to sell products online.",
        detailedDescription:"More things to explain here.",
        technologies: ["Node.js", "Express", "MySQL", "Vue.js", "Java"],
        link: "https://github.com/NkaLight/store-system",
        skillDescription: "Server-side web-development,Implementing the Middleware and implementing a MySQL database to store my data, to fullfill functional requirements, based on my information gathering with an arbitary client, as part of my INFO202 assignment. The more technical aspects I expanded was unit testing, and the importance of good code coverage.",
        startDate: "2024-03-01",
        endDate: "2024-09-30",
    },
    {
        id: 3,
        name: "Project Andie",
        description: "A Java based A non-destructive image editor, with a plathora of features",
        detailedDescription:"More things to explain here.",
        technologies: ["Java", "OOP", "JUnit testing"],
        link: "https://github.com/NkaLight/Project-Andie",
        skillDescription: "Learn't about the importance of working in a team, where we would delegate work very early on every week, and work on our specific project tasks for the week. I also learnt about the importance of asking for help and how efficient software development becomes in a collaborative dev team.",
        startDate: "2023-01-15",
        endDate: "2023-6-03",
    },
    {
        id: 4,
        name: "Bug Bounty Hunter course",
        description: "Using Hack the box platform to learn about cybersecurity",
        detailedDescription:"More things to explain here.",
        technologies: ["Linux", "Powershell", "Cmd", "Wireshark", "Burpsuite", "Bash"],
        link: "https://academy.hackthebox.com/achievement/1521618/35",
        skillDescription: "Learn't about various tools, and concepts used to perform various attacks, I understand and I am in the process of having an even deeper understanding of technologies, used in large corporations such as Active directories.",
        startDate: "2024-10-28",
        endDate: "present",
    },
];

export default projects;
